// src/components/features/Jobs/JobForm.js

import React, { useState, useEffect } from 'react';
import { toast } from 'sonner';
import { Loader2, ArrowLeft, ArrowRight, Wallet, Check, Sparkles, Paperclip, Upload, X, FileText } from 'lucide-react';
import FormInput from '../../common/FormInput';
import Button from '../../common/Button';
import MultiSelectSkills from '../../common/MultiSelectSkills';
import jobService from '../../../services/jobService'; //
import aiService from '../../../services/aiService';
import categoryService from '../../../services/categoryService';
import Stepper from '../../common/Stepper'; // Assuming this component exists

const inputStyle = "block w-full px-3 py-2 border border-border rounded-md shadow-sm placeholder-text-light focus:outline-none focus:ring-2 focus:ring-primary-light focus:border-transparent sm:text-md disabled:opacity-70 disabled:bg-gray-100";
const TOTAL_STEPS = 4;

const formSteps = [
    { id: 1, name: 'Job Details' },
    { id: 2, name: 'Attachments' },
    { id: 3, name: 'Skills & Scope' },
    { id: 4, name: 'Budget' },
];

/**
 * Helper function to format file size
 */
const formatFileSize = (bytes, decimalPoint = 2) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const dm = decimalPoint < 0 ? 0 : decimalPoint;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
};

/**
 * Validates the current step's data before proceeding.
 * @param {number} step - Current step number.
 * @param {object} formData - Current form data.
 * @returns {boolean} - True if validation passes, false otherwise.
 */
const validateStep = (step, formData) => {
    switch (step) {
        case 1:
            if (!formData.title.trim() || !formData.description.trim()) {
                toast.error('Title and Description are required.');
                return false;
            }
            if (!formData.category) {
                toast.error('Please select a job category.');
                return false;
            }
            return true;
        case 2:
            // Attachments are optional, so this step always passes unless there's an error state
            return true;
        case 3:
            if (formData.skills.length === 0) {
                toast.error('Please select at least one required skill.');
                return false;
            }
            return true;
        case 4:
            if (formData.budget <= 0 || isNaN(formData.budget)) {
                toast.error('A valid budget amount is required.');
                return false;
            }
            return true;
        default:
            return true;
    }
};

/**
 * A multi-step form for clients to post a new job (or edit an existing one).
 * @param {object} props
 * @param {function} props.onFormSubmit - Callback for final form submission.
 * @param {boolean} props.submissionLoading - State to disable form during submission.
 * @param {string | null} props.submissionError - Error message from submission.
 * @param {string} props.aiGeneratedDescription - Description generated by the AI assistant.
 * @param {boolean} props.isEditMode - New prop: Whether the form is in edit mode.
 * @param {object | null} props.initialData - New prop: Initial job data for editing.
 */
const JobForm = ({ onFormSubmit, submissionLoading, submissionError, aiGeneratedDescription, isEditMode, initialData }) => {
    const defaultFormData = {
        title: '',
        description: '',
        category: '', // Category ID
        location: 'Remote',
        skills: [], // Array of skill IDs
        budget: 0,
        currency: 'USD',
        attachments: [], // Array of File objects
    };

    const [step, setStep] = useState(1);
    // Initialize state with default data OR initialData if available for edit mode
    const [formData, setFormData] = useState(initialData || defaultFormData);
    
   
    
    const [categories, setCategories] = useState([]);
    const [loadingCategories, setLoadingCategories] = useState(true);
    const [categoryError, setCategoryError] = useState(null);
    const [suggestedPrice, setSuggestedPrice] = useState(null);
    const [priceLoading, setPriceLoading] = useState(false);

    // --- Effects ---

    // 0. Update form data when initialData loads (only relevant if initialData loads asynchronously,
    // which it does via the parent component's useEffect).
    // This is crucial for pre-populating the form once data is fetched in edit mode.
    useEffect(() => {
        if (isEditMode && initialData) {
            setFormData(prev => ({
                ...prev,
                ...initialData,
          
                attachments: [], 
                // Budget needs to be parsed to a number for the form input
                budget: Number(initialData.budget) || 0, 
            }));
        }
    }, [isEditMode, initialData]);

    // 1. Fetch Categories on mount (No change)
    useEffect(() => {
        const fetchCategories = async () => {
            try {
                const data = await categoryService.getActiveCategories();
                setCategories(data);
            } catch (err) {
                console.error("Failed to fetch categories:", err);
                setCategoryError("Failed to load job categories.");
            } finally {
                setLoadingCategories(false);
            }
        };
        fetchCategories();
    }, []);

    // 2. Apply AI-generated description (Only run if NOT in edit mode)
    useEffect(() => {
        // Only apply AI suggestion if NOT editing an existing job
        if (!isEditMode && aiGeneratedDescription && step === 1) {
            setFormData(prev => ({
                ...prev,
                description: aiGeneratedDescription
            }));
        }
    }, [aiGeneratedDescription, step, isEditMode]);


    // 3. Suggest Price when relevant fields change on Step 4 (Optional: Disable in Edit Mode to save API calls)
    useEffect(() => {
        // Disable AI price suggestion when editing
        if (isEditMode) {
            setSuggestedPrice(null);
            return;
        }

        // Existing logic for price suggestion
        if (step === 4 && formData.description.length > 50 && formData.skills.length > 0 && !priceLoading) {
            const getSuggestion = async () => {
                setPriceLoading(true);
                setSuggestedPrice(null);
                try {
                    const price = await aiService.suggestJobPrice(formData.description, formData.skills);
                    setSuggestedPrice(price);
                } catch (error) {
                    console.error("AI Price Suggestion Failed:", error);
                    // Fail silently for UX
                } finally {
                    setPriceLoading(false);
                }
            };
            // Debounce the call to avoid excessive API calls
            const handler = setTimeout(getSuggestion, 1500);
            return () => clearTimeout(handler);
        }
    }, [step, formData.description, formData.skills, isEditMode]); // Added isEditMode to dependency array


    // --- Handlers ---

    const handleChange = (e) => {
        const { id, value, type, checked } = e.target;
        // Handle budget as a number
        const newValue = id === 'budget' ? (value === '' ? '' : Number(value)) : type === 'checkbox' ? checked : value;

        setFormData(prev => ({
            ...prev,
            [id]: newValue
        }));
    };

    const handleNext = () => {
        if (validateStep(step, formData)) {
            setStep(prev => Math.min(prev + 1, TOTAL_STEPS));
        }
    };

    const handleBack = () => {
        setStep(prev => Math.max(prev - 1, 1));
    };

    const handleFileSelect = (file) => {
        if (formData.attachments.length >= 5) {
            toast.error("You can upload a maximum of 5 files.");
            return;
        }

        // Basic check for file type
        const allowedTypes = ['image/jpeg', 'image/png', 'application/pdf', 'application/zip', 'text/plain'];
        if (!allowedTypes.includes(file.type)) {
            toast.error(`File type '${file.type}' is not supported. Please use image, PDF, zip, or text files.`);
            return;
        }

        // Basic check for file size (5MB limit)
        if (file.size > 5 * 1024 * 1024) {
            toast.error(`File size exceeds 5MB limit.`);
            return;
        }

        setFormData(prev => ({
            ...prev,
            attachments: [...prev.attachments, file]
        }));
    };

    const handleFileRemove = (index) => {
        setFormData(prev => ({
            ...prev,
            attachments: prev.attachments.filter((_, i) => i !== index)
        }));
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if (validateStep(TOTAL_STEPS, formData)) {
            // Convert form data to a FormData object for file uploads
            const dataToSubmit = new FormData();

            // Append all non-file fields
            dataToSubmit.append('title', formData.title);
            dataToSubmit.append('description', formData.description);
            dataToSubmit.append('category', formData.category);
            dataToSubmit.append('location', formData.location);
            // Ensure budget is passed as a string or number, not empty string
            dataToSubmit.append('budget', formData.budget); 
            dataToSubmit.append('currency', formData.currency);
            // Append skills as an array of IDs
            formData.skills.forEach(skillId => {
                dataToSubmit.append('skills[]', skillId._id);
            });
            // Append files
            formData.attachments.forEach(file => {
                dataToSubmit.append('attachments', file, file.name); // 'attachments' is the field name on the server
            });

            // Pass the FormData object to the parent handler
            onFormSubmit(dataToSubmit);
        }
    };


    // --- Step 1: Job Details ---
    const renderStep1 = () => (
        <div className="space-y-6">
            <h2 className="text-xl font-semibold text-text-primary">{isEditMode ? 'Modify Job Details' : 'What do you need done?'}</h2>

            <FormInput
                id="title"
                label="Job Title"
                type="text"
                value={formData.title}
                onChange={handleChange}
                placeholder="e.g., Install new kitchen cabinets"
                required
                maxLength={100}
            />

            <div className="flex flex-col">
                <label htmlFor="description" className="block text-sm font-medium text-text-secondary mb-1">
                    Job Description <span className="text-red-500">*</span>
                </label>
                <textarea
                    id="description"
                    value={formData.description}
                    onChange={handleChange}
                    rows={8}
                    className={inputStyle}
                    placeholder="Provide a clear and detailed description of the work, including scope, materials, access, and desired outcome."
                    required
                />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="relative">
                    <label htmlFor="category" className="block text-sm font-medium text-text-secondary mb-1">
                        Select Category <span className="text-red-500">*</span>
                    </label>
                    {loadingCategories ? (
                        <div className="flex items-center space-x-2 p-2 border border-border rounded-md bg-gray-50">
                            <Loader2 size={18} className="animate-spin text-primary" />
                            <span className="text-sm text-text-secondary">Loading categories...</span>
                        </div>
                    ) : categoryError ? (
                        <p className="text-sm text-red-500">{categoryError}</p>
                    ) : (
                        <select
                            id="category"
                            value={formData.category}
                            onChange={handleChange}
                            className={inputStyle}
                            required
                        >
                            <option value="">Select a trade professional category</option>
                            {categories.map(cat => (
                                <option key={cat._id} value={cat._id}>{cat.name}</option>
                            ))}
                        </select>
                    )}
                </div>

                <FormInput
                    id="location"
                    label="Location / Work Type"
                    type="text"
                    value={formData.location}
                    onChange={handleChange}
                    placeholder="e.g., Remote, London, SW1A 0AA"
                    required
                />
            </div>

            {/* AI Assistant Tip: Only relevant if NOT in edit mode OR if description came from AI */}
            {!isEditMode && (
                <div className="text-sm p-3 bg-blue-50 border border-blue-200 text-blue-800 rounded-md flex items-start">
                    <Sparkles size={18} className="mr-3 mt-0.5 flex-shrink-0" />
                    <div>
                        <span className="font-semibold">AI Assistant Tip:</span>
                        If you used the AI Assistant, the suggested description is pre-filled above. You can still edit it!
                    </div>
                </div>
            )}
        </div>
    );

    // --- Step 2: Attachments ---
    const renderStep2 = () => (
        <div className="space-y-6">
            <h2 className="text-xl font-semibold text-text-primary">Add Project Attachments</h2>
            <p className="text-text-secondary">Upload drawings, photos, or documents to help professionals understand the scope. (Max 5 files, 5MB each)</p>

            {/* Simple Drop-in File Uploader */}
            <div
                className={`flex justify-center px-6 pt-5 pb-6 border-2 border-border border-dashed rounded-md transition-colors cursor-pointer hover:border-primary-light`}
                onClick={() => document.getElementById('file-upload-input').click()}
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => {
                    e.preventDefault();
                    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
                        handleFileSelect(e.dataTransfer.files[0]);
                    }
                }}
            >
                <div className="space-y-1 text-center">
                    <Upload className="mx-auto h-12 w-12 text-text-light" />
                    <div className="flex text-sm text-text-secondary justify-center">
                        <button
                            type="button"
                            className="relative font-medium text-primary hover:underline focus:outline-none"
                        >
                            Upload a file
                        </button>
                        <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-text-light">
                        PNG, JPG, PDF, ZIP, TXT up to 5MB
                    </p>
                </div>
                <input
                    id="file-upload-input"
                    type="file"
                    className="sr-only"
                    onChange={(e) => {
                        if (e.target.files && e.target.files[0]) {
                            handleFileSelect(e.target.files[0]);
                            e.target.value = null; // Reset input for next selection
                        }
                    }}
                    accept="image/*,.pdf,.zip,text/plain"
                    multiple // Allow multiple file selection
                />
            </div>

            {/* File List */}
            {formData.attachments.length > 0 && (
                <div className="space-y-3 p-4 border border-border rounded-md bg-gray-50">
                    <h3 className="font-medium text-text-primary flex items-center">
                        <Paperclip size={18} className="mr-2" /> Attached Files ({formData.attachments.length})
                    </h3>
                    {formData.attachments.map((file, index) => (
                        <div key={index} className="flex items-center justify-between p-3 border border-border bg-white rounded-md shadow-sm">
                            <div className="flex items-center overflow-hidden">
                                <FileText size={20} className="text-primary mr-3 flex-shrink-0" />
                                <div className="truncate">
                                    <p className="text-sm font-medium truncate">{file.name}</p>
                                    <p className="text-xs text-text-light">{formatFileSize(file.size)}</p>
                                </div>
                            </div>
                            <button
                                type="button"
                                onClick={() => handleFileRemove(index)}
                                className="text-text-light hover:text-red-500 transition-colors ml-4 p-1 rounded-full hover:bg-red-50"
                                title="Remove file"
                            >
                                <X size={16} />
                            </button>
                        </div>
                    ))}
                </div>
            )}
            {/* NOTE: In a real edit scenario, you would list existing files here (from initialData) 
                and provide a way to mark them for deletion, separate from new uploads (formData.attachments). 
                For this change, only *new* files are tracked in formData.attachments, 
                and the parent component's updateJob function would need to handle existing files 
                (which is outside the scope of this request). */}
        </div>
    );

    // --- Step 3: Skills & Scope ---
    const renderStep3 = () => (
        <div className="space-y-6">
            <h2 className="text-xl font-semibold text-text-primary">Specify Required Skills and Scope</h2>
            <p className="text-text-secondary">Select the key skills a professional must have and define the level of expertise required.</p>

            <MultiSelectSkills
                label="Required Skills"
                placeholder="Select skills..."
                selectedSkills={formData.skills}
                onChange={(skillIds) => setFormData(prev => ({ ...prev, skills: skillIds }))}
                categoryId={formData.category} // Pass category ID to filter skills
            />

 
        </div>
    );

    // --- Step 4: Budget ---
    const renderStep4 = () => (
        <div className="space-y-6">
            <h2 className="text-xl font-semibold text-text-primary">Set Your Budget</h2>
            <p className="text-text-secondary">This is the total amount you are willing to pay for the project.</p>

            <div className="flex flex-col sm:flex-row gap-4">
                <FormInput
                    id="budget"
                    label={`Project Budget (${formData.currency})`}
                    type="number"
                    value={formData.budget}
                    onChange={handleChange}
                    placeholder="e.g., 500"
                    required
                    min="1"
                    step="1"
                    className="flex-grow"
                />

                <div className="sm:w-32">
                    <FormInput
                        id="currency"
                        label="Currency"
                        type="text"
                        value={formData.currency}
                        onChange={handleChange}
                        disabled
                    />
                </div>
            </div>

            {/* AI Price Suggestion Feature - Hidden in Edit Mode */}
            {!isEditMode && (
                <>
                    {priceLoading && (
                        <div className="flex items-center space-x-3 p-4 bg-yellow-50 border border-yellow-200 rounded-md">
                            <Loader2 size={20} className="animate-spin text-yellow-700 flex-shrink-0" />
                            <p className="text-sm text-yellow-800">Calculating recommended price based on job details...</p>
                        </div>
                    )}

                    {suggestedPrice && !priceLoading && (
                        <div className="flex items-center space-x-3 p-4 bg-green-50 border border-green-200 rounded-md">
                            <Wallet size={20} className="text-green-700 flex-shrink-0" />
                            <p className="text-sm text-green-800">
                                <span className="font-semibold">AI Price Suggestion:</span> Based on similar jobs and skills, a fair budget range is <span className="font-bold">${suggestedPrice.min.toFixed(0)} - ${suggestedPrice.max.toFixed(0)}</span>.
                            </p>
                        </div>
                    )}
                </>
            )}

            <div className="p-3 bg-blue-50 border border-blue-200 text-blue-800 rounded-md">
                <p className="text-sm font-medium">Note: Your budget is a fixed price. We use a secure escrow system to hold your funds until the work is completed and approved by you.</p>
            </div>
        </div>
    );


    // --- Main Render ---
    return (
        <form onSubmit={handleSubmit} className="space-y-8">
            <Stepper currentStep={step} steps={formSteps} />

            <div className="min-h-[400px]">
                {step === 1 && renderStep1()}
                {step === 2 && renderStep2()}
                {step === 3 && renderStep3()}
                {step === 4 && renderStep4()}
            </div>

            {submissionError && (
                <div className="p-3 text-red-700 bg-red-100 border border-red-300 rounded-md">
                    Submission Error: {submissionError}
                </div>
            )}

            {/* Navigation Buttons */}
            <div className="flex justify-between border-t pt-4">
                <Button
                    type="button"
                    variant="secondary"
                    onClick={handleBack}
                    disabled={step === 1 || submissionLoading}
                    className={`${step === 1 ? 'invisible' : 'visible'} flex items-center justify-center`}
                >
                    <ArrowLeft size={16} className="mr-2" /> Back
                </Button>

                {step < TOTAL_STEPS && (
                    <Button
                        type="button"
                        variant="primary"
                        onClick={handleNext}
                        disabled={submissionLoading}
                        className='flex justify-center items-center'
                    >
                        Next <ArrowRight size={16} className="ml-2" />
                    </Button>
                )}

                {step === TOTAL_STEPS && (
                    <Button
                        type="submit"
                        variant="primary"
                        disabled={submissionLoading || !formData.budget}
                        className='flex justify-center items-center'

                    >
                        {submissionLoading ? <Loader2 size={18} className="mr-2 animate-spin" /> : <Check size={18} className="mr-2" />}
                        {submissionLoading ? (isEditMode ? 'Updating Job...' : 'Posting Job...') : (isEditMode ? 'Save Changes' : 'Post Job')}
                    </Button>
                )}
            </div>
        </form>
    );
};

export default JobForm;